{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: cluster-monitoring
    source: rancher-monitoring
  name: hello-world-app
  namespace: cattle-prometheus
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
{{- end -}}